image: Visual Studio 2019

version: '{build}'

pull_requests:
  do_not_increment_build_number: true

nuget:
  disable_publish_on_pr: true

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  github_access_token:
    secure: sNbY3i/5Yvdl9K+elyCNoCbZj+pdJ9EmeyxPg0KcIY57BlJ6gQ4pwsQKkb45rgoV

cache:
  - tools -> build.cake
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - '%USERPROFILE%\.nuget\packages -> **\*.csproj'

init:
  - git config --global user.email "ci@appveyor.com"
  - git config --global user.name "AppVeyor CI"
  - git config --global credential.helper store
  - ps: Add-Content -Path "$HOME\.git-credentials" -Value "https://$($env:github_access_token):x-oauth-basic@github.com`n" -NoNewline

install:
  - choco install docfx -y --version=2.56.6
  - dotnet tool restore

build_script:
  - dotnet tool run dotnet-cake -- --target=AppVeyor

test: off

artifacts:
- path: .\artifacts\nuget\*
  name: NuGet
- path: .\artifacts\**\*.zip
  name: Archive
- path: .\artifacts\opencover-results.xml
  name: OpenCover
- path: .\artifacts\coverage-report
  name: Coverage

deploy:
- provider: NuGet
  #server: https://api.nuget.org/v3/index.json
  name: production
  api_key:
    secure: A56Qs5ovDCqFsic8ntEtyzli2cLE/D9UZb6adpWOaSrVNLEy+mmPgMijjimmjj0i
  artifact: NuGet
  on:
    appveyor_repo_tag: true
- provider: NuGet
  server: https://nuget.pkg.github.com/chroma-sdk/index.json
  name: production
  username: Sharparam
  skip_symbols: true
  api_key:
    secure: sNbY3i/5Yvdl9K+elyCNoCbZj+pdJ9EmeyxPg0KcIY57BlJ6gQ4pwsQKkb45rgoV
  artifact: NuGet
  on:
    appveyor_repo_tag: true
- provider: GitHub
  description: Automatically created by AppVeyor.
  auth_token:
    secure: sNbY3i/5Yvdl9K+elyCNoCbZj+pdJ9EmeyxPg0KcIY57BlJ6gQ4pwsQKkb45rgoV
  artifact: NuGet,Archive,OpenCover,Coverage
  draft: true
  on:
    appveyor_repo_tag: true
- provider: NuGet
  server: https://nuget.pkg.github.com/chroma-sdk/index.json
  name: development
  username: Sharparam
  skip_symbols: true
  api_key:
    secure: sNbY3i/5Yvdl9K+elyCNoCbZj+pdJ9EmeyxPg0KcIY57BlJ6gQ4pwsQKkb45rgoV
  artifact: NuGet
  on:
    branch: develop

after_deploy:
- ps: .\appveyor\deploy-docs.ps1

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

notifications:
- provider: GitHubPullRequest
- provider: Slack
  auth_token:
    secure: QUZYn9cOzpULl4DByhENnUcKSsv035vR3PSgX8JqUqs0S4ZPVct+slZKrUB6xKXD
  channel: '#colore'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
- provider: Webhook
  url: https://webhooks.gitter.im/e/a034d0036043d620fe38
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
